name: Trabalhando com outputs

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: build
        run: |
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
    outputs:
      build-status: ${{ steps.build.outputs.output1 }}
      output2: ${{ steps.build.outputs.output2 }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: |
          echo "Valor do output1: ${{ needs.build.outputs.build-status }}"
          echo "Valor do output2: ${{ needs.build.outputs.output2 }}"